baseURL: "https://hugo-papermod-tags-v1.netlify.app"
title: CsendesBlog
languageCode: en
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    # minifyOutput: true
           
languages:
      
      en: 
        languageName: ":en:"
        weight: 2   
        menu:
            main:
                - name: Bookmarks
                  url: bookmarks/
                  weight: 5
                - name: Opensource
                  url: opensource/
                  weight: 5
                - name: Categories
                  url: categories/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Search
                  url: archive/
                  weight: 20
                - name: Archive
                  url: archives
                  weight: 20
                - name: About
                  url: about/
                  weight: 20
                
                
 
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
params:
    env: production
    title: "22940dev Github blog"
    tagline: "GitHub  PaperMod"
    description: "Hugo papermod template."
    author: 22940dev
    GitHubUser: "22940dev"
    LinkedInUser: "doc22940"
    TwitterUser: "alec"
    
    
    # author: ["Me", "You"] # multiple authors

    images: ["<link or path of image for opengraph, twitter-cards>"]

    ShowReadingTime: true
    ShowShareButtons: true
    comments: true
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false
        

   # assets:
    #    favicon: "<link / abs url>"
    #    favicon16x16: "<link / abs url>"
    #    favicon32x32: "<link / abs url>"
    #    apple_touch_icon: "<link / abs url>"
    #    safari_pinned_tab: "<link / abs url>"

    label:
        text: "CsendesBlog"   
  # profile-mode
    profileMode:
       enabled: false # needs to be explicitly set
       Title: "CsendesBlog"
       Content: testing
        buttons:
           - name: Posts
           url: posts
           - name: Tags
           url: tags

        # imageUrl: '<img location>'
        # imageTitle: my image
       
    # home-info mode
    homeInfoParams:
        Title: "Hi There \U0001F44B"
        Content: This is my Github page/blog abut useful web tools. I started it for learning purposes. I would like to improve my programming knowledge. I am interested in productivity tools, data management and cloud services on multiple platforms.

    socialIcons:
        - name: github
          url: "https://github.com/22940dev"
        - name: linkedin
          url: "https://linkedin.com/doc22940"  
        - name: twitter
          url: "https://twitter.com/alec"
     
    

menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: about
          url: /about/
          weight: 30
